two pointers
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   Two Pointers.py

PS C:\Users\Shukla\prep2025\ByteByteGo> git commit -m
error: switch `m' requires a valueS C:\Users\Shukla\prep2025\ByteByteGo> git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   Two Pointers.py

PS C:\Users\Shukla\prep2025\ByteByteGo> git commit -m
error: switch `m' requires a value